/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_younglee_retrofittest_safe_Tag */

#ifndef _Included_com_younglee_retrofittest_safe_Tag
#define _Included_com_younglee_retrofittest_safe_Tag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_younglee_retrofittest_safe_Tag
 * Method:    getTag
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_younglee_retrofittest_safe_Tag_getTag
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
